# wrangler.toml
name = "faktum-newsletter"
main = "dist/_worker.js"
compatibility_date = "2025-12-04"
type = "javascript"

[vars]
RESEND_API_KEY = "set_in_dashboard_or_leave_blank_here"

[site]
bucket = "./dist"
entry-point = "workers-site"

